version: 1

genesis:
    app_state:
      ysip:
        minter: "ysip102xnfc6d5j8j7tshq3yrg0t7kr8tsd2y242ku0"
      bank:
        denom_metadata:
          - description: "The native token of ysip chain"
            display: "ukrw"
            base: "ukrw"
            name: "microKRW"
            symbol: "KRW"
            denom_units:
              - denom: "ukrw"
                exponent: "0"
          - description: "The native staked token of ysip chain"
            display: "uskrw"
            base: "uskrw"
            name: "microStakedKRW"
            symbol: "sKRW"
            denom_units:
              - denom: "uskrw"
                exponent: "0"
      staking:
          params:
            bond_denom: "uskrw"
accounts:
  - name: validator
    coins: ["1000000ukrw", "1000000uskrw"]
validators:
  - name: validator
    bonded: "1000000uskrw"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"

init:
  app:
    minimum-gas-prices: "0ukrw"

