genesis:
    app_state:
      bank:
        denom_metadata:
          - description: "The native token of ysip chain"
            display: "krw"
            base: "ukrw"
            name: "KRW"
            symbol: "KRW"
            denom_units:
              - denom: "ukrw"
                exponent: "0"
              - denom: "mkrw"
                exponent: "3"
              - denom: "krw"
                exponent: "6"
          - description: "The native staked token of ysip chain"
            display: "skrw"
            base: "uskrw"
            name: "stakedKRW"
            symbol: "sKRW"
            denom_units:
              - denom: "uskrw"
                exponent: "0"
              - denom: "mskrw"
                exponent: "3"
              - denom: "skrw"
                exponent: "6"
      staking:
          params:
            bond_denom: "skrw"
accounts:
  - name: validator
    coins: ["1krw", "10000000skrw"]
validator:
  name: validator
  staked: "10000000skrw"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
