accounts:
  - name: genesis_wallet
    coins: ["1000000ukrw"]
validator:
  name: validator
  staked: "1000000ukrw"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
